import Navbar from "@/components/Navbar";
import AuthProvider from "@/providers/AuthProvider";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Eventry | A Next js Event Calendar",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body>
                <AuthProvider>
                    <Navbar />
                    <main className='py-8'>{children}</main>
                    <ToastContainer position='bottom-right' />
                </AuthProvider>
            </body>
        </html>
    );
}

