import Navbar from "@/components/Navbar";
import { ConnectToMongoDB } from "@/services/mongoDB";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Eventry | A Next js Event Calendar",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    await ConnectToMongoDB();
    return (
        <html lang='en'>
            <body>
                <Navbar />
                <main className='py-8'>{children}</main>
            </body>
        </html>
    );
}

